### ISSUE TITLE
Use proof subscriptions/blocking call instead of polling in client/operator communication

### ISSUE THREAD

**Issue by sebastianst** [perun-network/erdstall#41]
The client currently polls the operator for fresh deposit and balance proofs. It would be better to either
1. use a subscription instead or
2. make the call blocking, like the enclave call already is.

The issue with 2. might be that it only works on a very stable and uninterrupted connection between client and op. But it would be more straight forward to change the current implementation to that.

**Comment by matthiasgeihs** [comment]
Can you say a few words on why you think blocking calls "would be better"? Is there an issue with the current approach? Which problem do blocking calls solve?

Initially, I considered implementing blocking calls. However, I decided in favor of the current method, because I think this potentially allows for a less complex operator logic and a more stable connection.

**Comment by matthiasgeihs** [comment]
We just had a call on this issue. The idea is that we use a subscription instead of polling in order to reduce network congestion. We should not try to implement a custom subscription functionality on top of the currently rpc package, but use a communication framework that provides subscription functionality built in. The technology should also be supported within browsers so that we can use if we decide to build a web client. Candidates are web sockets via [Gorilla](https://github.com/gorilla/websocket) and gRPC via [grpc-web](https://github.com/improbable-eng/grpc-web/).

**Comment by sebastianst** [comment]
(And feedback on the client's side is immediate. E.g. if the polling interval is 1 sec, from the moment the proof is generated until it is fetched by the client, 1 sec might pass, resulting in a noticeable delay when, e.g., logging a new proof.)
